import Link from 'next/link';
import { source } from '@/lib/source';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import recentUpdates from '@/data/recent-updates.json';

// Landing page for claude-almanac.sivura.com. Server component only — all
// data (guides, case studies, recent updates) is collected at build time.
//
// Sections:
//   1. Hero with title + tagline + CTAs
//   2. Category grid (8 reference categories, links to representative docs)
//   3. Guides + Case studies lists (from the fumadocs source collections)
//   4. Recent updates (generated by scripts/recent-updates.mjs at build time)
//   5. "For agents" — machine-friendly endpoints

const TAGLINE =
  'A knowledge base for humans and AI agents — Claude Code features, configurations, and workflows. By Alexander Sivura.';

type Category = {
  title: string;
  description: string;
  href: string;
};

const categories: Category[] = [
  {
    title: 'Core',
    description: 'Hooks, skills, settings, rules, tools, memory.',
    href: '/docs/hooks',
  },
  {
    title: 'Agents',
    description: 'Sub-agents, agent teams, plugins.',
    href: '/docs/agents',
  },
  {
    title: 'Integrations',
    description: 'MCP, Slack, channels.',
    href: '/docs/mcp-servers',
  },
  {
    title: 'Security',
    description: 'Sandbox, auto-mode.',
    href: '/docs/security-sandbox',
  },
  {
    title: 'CI/CD',
    description: 'Actions, GitLab, code review, scheduled tasks.',
    href: '/docs/github-actions',
  },
  {
    title: 'Surfaces',
    description: 'IDE, SDK, remote, voice, computer use.',
    href: '/docs/ide-integrations',
  },
  {
    title: 'Workflows',
    description: 'Checkpointing, ultraplan, pricing.',
    href: '/docs/checkpointing',
  },
  {
    title: 'Foundational',
    description: 'Architecture, .claude directory.',
    href: '/docs/how-claude-code-works',
  },
];

type CollectionPage = {
  url: string;
  title: string;
};

function collectByType(type: 'guide' | 'caseStudy'): CollectionPage[] {
  const pages: CollectionPage[] = [];
  for (const page of source.getPages()) {
    const discriminator = (page.data as { type?: string }).type;
    if (discriminator !== type) continue;
    pages.push({ url: page.url, title: page.data.title });
  }
  pages.sort((a, b) => a.title.localeCompare(b.title));
  return pages;
}

export default function HomePage() {
  const guides = collectByType('guide');
  const caseStudies = collectByType('caseStudy');

  return (
    <main className="flex-1 px-4 py-12 md:py-16 lg:py-20">
      <div className="mx-auto flex max-w-5xl flex-col gap-16">
        {/* Hero */}
        <section className="flex flex-col gap-6">
          <h1 className="text-4xl font-bold tracking-tight md:text-5xl lg:text-6xl">
            Claude Code Almanac
          </h1>
          <p className="max-w-2xl text-lg italic leading-relaxed text-foreground/80 md:text-xl">
            A knowledge base for humans and AI agents —
            <br />
            Claude Code features, configurations, and workflows.
          </p>
          <p className="text-sm text-muted-foreground">
            By Alexander Sivura.
          </p>
          <div className="flex flex-wrap gap-3">
            <Link
              href="/docs"
              className="inline-flex items-center justify-center rounded-md bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
            >
              Browse docs →
            </Link>
            <a
              href="https://github.com/asivura/claude-almanac"
              className="inline-flex items-center justify-center rounded-md border border-border bg-background px-5 py-2.5 text-sm font-medium text-foreground transition-colors hover:bg-accent"
            >
              GitHub →
            </a>
          </div>
        </section>

        {/* Category grid */}
        <section className="flex flex-col gap-6">
          <h2 className="text-2xl font-semibold tracking-tight">
            Browse by category
          </h2>
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
            {categories.map((cat) => (
              <Link
                key={cat.href}
                href={cat.href}
                className="group block h-full"
              >
                <Card className="h-full transition-colors group-hover:border-primary group-hover:bg-accent">
                  <CardHeader>
                    <CardTitle className="text-base group-hover:text-primary">
                      {cat.title}
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground">
                      {cat.description}
                    </p>
                  </CardContent>
                </Card>
              </Link>
            ))}
          </div>
        </section>

        {/* Guides + Case studies */}
        <section className="grid grid-cols-1 gap-8 md:grid-cols-2">
          <div className="flex flex-col gap-4">
            <h2 className="text-2xl font-semibold tracking-tight">Guides</h2>
            {guides.length === 0 ? (
              <p className="text-sm text-muted-foreground">
                No guides yet.
              </p>
            ) : (
              <ul className="flex flex-col gap-2">
                {guides.map((g) => (
                  <li key={g.url}>
                    <Link
                      href={g.url}
                      className="text-sm text-foreground underline-offset-4 hover:text-primary hover:underline"
                    >
                      {g.title}
                    </Link>
                  </li>
                ))}
              </ul>
            )}
          </div>
          <div className="flex flex-col gap-4">
            <h2 className="text-2xl font-semibold tracking-tight">
              Case studies
            </h2>
            {caseStudies.length === 0 ? (
              <p className="text-sm text-muted-foreground">
                No case studies yet.
              </p>
            ) : (
              <ul className="flex flex-col gap-2">
                {caseStudies.map((cs) => (
                  <li key={cs.url}>
                    <Link
                      href={cs.url}
                      className="text-sm text-foreground underline-offset-4 hover:text-primary hover:underline"
                    >
                      {cs.title}
                    </Link>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </section>

        {/* Recent updates */}
        <section className="flex flex-col gap-4">
          <h2 className="text-2xl font-semibold tracking-tight">
            Recent updates
          </h2>
          {recentUpdates.length === 0 ? (
            <p className="text-sm text-muted-foreground">No updates yet.</p>
          ) : (
            <ul className="flex flex-col gap-2">
              {recentUpdates.map((entry) => (
                <li
                  key={entry.hash}
                  className="text-sm text-muted-foreground"
                >
                  <span className="font-mono">{entry.date}</span>
                  <span className="mx-2">·</span>
                  <span className="text-foreground">{entry.subject}</span>
                </li>
              ))}
            </ul>
          )}
        </section>

        {/* For agents */}
        <section className="flex flex-col gap-4 rounded-lg border border-border bg-card p-6">
          <h2 className="text-2xl font-semibold tracking-tight">For agents</h2>
          <p className="text-sm text-muted-foreground">
            Machine-friendly endpoints for LLM ingestion:
          </p>
          <ul className="flex flex-col gap-2 text-sm">
            <li>
              <Link
                href="/llms.txt"
                className="font-mono text-primary underline-offset-4 hover:underline"
              >
                /llms.txt
              </Link>
              <span className="ml-2 text-muted-foreground">
                — index of all pages
              </span>
            </li>
            <li>
              <Link
                href="/llms-full.txt"
                className="font-mono text-primary underline-offset-4 hover:underline"
              >
                /llms-full.txt
              </Link>
              <span className="ml-2 text-muted-foreground">
                — full content, concatenated
              </span>
            </li>
            <li>
              <span className="font-mono text-foreground">
                Accept: text/markdown
              </span>
              <span className="ml-2 text-muted-foreground">
                on any <span className="font-mono">/docs/*</span> URL returns raw markdown
              </span>
            </li>
          </ul>
        </section>
      </div>
    </main>
  );
}
